package com.shu.onlinesell.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.shu.onlinesell.bean.OrderDetail;
import com.shu.onlinesell.enums.OrderStatusEnum;
import com.shu.onlinesell.enums.PayStatusEnum;
import com.shu.onlinesell.util.EnumUtil;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class OrderMasterDTO {
    private List<OrderDetail> orderDetailList;

    private String stringCreateTime;

    private String stringUpdateTime;

    private String stringFinishTime=null;

    public String getStringUpdateTime() {
        return stringUpdateTime;
    }

    public void setStringUpdateTime(String stringUpdateTime) {
        this.stringUpdateTime = stringUpdateTime;
    }

    public String getStringFinishTime() {
        return stringFinishTime;
    }

    public void setStringFinishTime(String stringFinishTime) {
        this.stringFinishTime = stringFinishTime;
    }


    public String getStringCreateTime() {
        return stringCreateTime;
    }

    public void setStringCreateTime(String stringCreateTime) {
        this.stringCreateTime = stringCreateTime;
    }

    public List<OrderDetail> getOrderDetailList() {
        return orderDetailList;
    }

    public void setOrderDetailList(List<OrderDetail> orderDetailList) {
        this.orderDetailList = orderDetailList;
    }


    @JsonIgnore
    public OrderStatusEnum getOrderStatusEnum() {
        return EnumUtil.getByCode(Integer.valueOf(orderStatus), OrderStatusEnum.class);
    }

    @JsonIgnore
    public PayStatusEnum getPayStatusEnum() {
        return EnumUtil.getByCode(Integer.valueOf(payStatus), PayStatusEnum.class);
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.table_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_name
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private String buyerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_status
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.total_amount
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Integer totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.consumption_money
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private BigDecimal consumptionMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.update_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.finish_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    private Date finishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_id
     *
     * @return the value of order_master.order_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_id
     *
     * @param orderId the value for order_master.order_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.table_id
     *
     * @return the value of order_master.table_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.table_id
     *
     * @param tableId the value for order_master.table_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_status
     *
     * @return the value of order_master.order_status
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_status
     *
     * @param orderStatus the value for order_master.order_status
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_id
     *
     * @return the value of order_master.buyer_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_id
     *
     * @param buyerId the value for order_master.buyer_id
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_name
     *
     * @return the value of order_master.buyer_name
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_name
     *
     * @param buyerName the value for order_master.buyer_name
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.pay_status
     *
     * @return the value of order_master.pay_status
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.pay_status
     *
     * @param payStatus the value for order_master.pay_status
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.total_amount
     *
     * @return the value of order_master.total_amount
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Integer getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.total_amount
     *
     * @param totalAmount the value for order_master.total_amount
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.consumption_money
     *
     * @return the value of order_master.consumption_money
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public BigDecimal getConsumptionMoney() {
        return consumptionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.consumption_money
     *
     * @param consumptionMoney the value for order_master.consumption_money
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setConsumptionMoney(BigDecimal consumptionMoney) {
        this.consumptionMoney = consumptionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.create_time
     *
     * @return the value of order_master.create_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.create_time
     *
     * @param createTime the value for order_master.create_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.update_time
     *
     * @return the value of order_master.update_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.update_time
     *
     * @param updateTime the value for order_master.update_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.finish_time
     *
     * @return the value of order_master.finish_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.finish_time
     *
     * @param finishTime the value for order_master.finish_time
     *
     * @mbg.generated Sun Apr 21 01:02:47 CST 2019
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
}