package com.shu.onlinesell.bean;

import java.util.Date;

public class EmployeeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.employee_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.employee_rank
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Byte employeeRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.employee_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.password
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.employee_id
     *
     * @return the value of employee_info.employee_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.employee_id
     *
     * @param employeeId the value for employee_info.employee_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.employee_rank
     *
     * @return the value of employee_info.employee_rank
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Byte getEmployeeRank() {
        return employeeRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.employee_rank
     *
     * @param employeeRank the value for employee_info.employee_rank
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setEmployeeRank(Byte employeeRank) {
        this.employeeRank = employeeRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.employee_name
     *
     * @return the value of employee_info.employee_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.employee_name
     *
     * @param employeeName the value for employee_info.employee_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.password
     *
     * @return the value of employee_info.password
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.password
     *
     * @param password the value for employee_info.password
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.create_time
     *
     * @return the value of employee_info.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.create_time
     *
     * @param createTime the value for employee_info.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.update_time
     *
     * @return the value of employee_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.update_time
     *
     * @param updateTime the value for employee_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}