package com.shu.onlinesell.bean;

import java.util.Date;

public class OrderKitchen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.detaill_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Integer detaillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.table_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.product_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.product_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.progress_status
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Byte progressStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_kitchen.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.detaill_id
     *
     * @return the value of order_kitchen.detaill_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Integer getDetaillId() {
        return detaillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.detaill_id
     *
     * @param detaillId the value for order_kitchen.detaill_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setDetaillId(Integer detaillId) {
        this.detaillId = detaillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.table_id
     *
     * @return the value of order_kitchen.table_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.table_id
     *
     * @param tableId the value for order_kitchen.table_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.product_id
     *
     * @return the value of order_kitchen.product_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.product_id
     *
     * @param productId the value for order_kitchen.product_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.product_name
     *
     * @return the value of order_kitchen.product_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.product_name
     *
     * @param productName the value for order_kitchen.product_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.progress_status
     *
     * @return the value of order_kitchen.progress_status
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Byte getProgressStatus() {
        return progressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.progress_status
     *
     * @param progressStatus the value for order_kitchen.progress_status
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setProgressStatus(Byte progressStatus) {
        this.progressStatus = progressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.create_time
     *
     * @return the value of order_kitchen.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.create_time
     *
     * @param createTime the value for order_kitchen.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_kitchen.update_time
     *
     * @return the value of order_kitchen.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_kitchen.update_time
     *
     * @param updateTime the value for order_kitchen.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}