package com.shu.onlinesell.bean;

import java.util.Date;

public class TableInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_info.table_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_info.table_amount
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Integer tableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_info.table_status
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Byte tableStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_info.table_id
     *
     * @return the value of table_info.table_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_info.table_id
     *
     * @param tableId the value for table_info.table_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_info.table_amount
     *
     * @return the value of table_info.table_amount
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Integer getTableAmount() {
        return tableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_info.table_amount
     *
     * @param tableAmount the value for table_info.table_amount
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setTableAmount(Integer tableAmount) {
        this.tableAmount = tableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_info.table_status
     *
     * @return the value of table_info.table_status
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Byte getTableStatus() {
        return tableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_info.table_status
     *
     * @param tableStatus the value for table_info.table_status
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setTableStatus(Byte tableStatus) {
        this.tableStatus = tableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_info.update_time
     *
     * @return the value of table_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_info.update_time
     *
     * @param updateTime the value for table_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}