package com.shu.onlinesell.bean;

import java.math.BigDecimal;
import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_phone
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_email
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_rank
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Byte userRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_prefer
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private String userPrefer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Consumption_times
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Integer consumptionTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.comsume_amount
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private BigDecimal comsumeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_phone
     *
     * @return the value of user_info.user_phone
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_phone
     *
     * @param userPhone the value for user_info.user_phone
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_email
     *
     * @return the value of user_info.user_email
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_email
     *
     * @param userEmail the value for user_info.user_email
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_rank
     *
     * @return the value of user_info.user_rank
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Byte getUserRank() {
        return userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_rank
     *
     * @param userRank the value for user_info.user_rank
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUserRank(Byte userRank) {
        this.userRank = userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_prefer
     *
     * @return the value of user_info.user_prefer
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public String getUserPrefer() {
        return userPrefer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_prefer
     *
     * @param userPrefer the value for user_info.user_prefer
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUserPrefer(String userPrefer) {
        this.userPrefer = userPrefer == null ? null : userPrefer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Consumption_times
     *
     * @return the value of user_info.Consumption_times
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Integer getConsumptionTimes() {
        return consumptionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Consumption_times
     *
     * @param consumptionTimes the value for user_info.Consumption_times
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setConsumptionTimes(Integer consumptionTimes) {
        this.consumptionTimes = consumptionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.comsume_amount
     *
     * @return the value of user_info.comsume_amount
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public BigDecimal getComsumeAmount() {
        return comsumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.comsume_amount
     *
     * @param comsumeAmount the value for user_info.comsume_amount
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setComsumeAmount(BigDecimal comsumeAmount) {
        this.comsumeAmount = comsumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}