package com.shu.onlinesell.dao;

import com.shu.onlinesell.bean.OrderKitchen;
import com.shu.onlinesell.bean.OrderKitchenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderKitchenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    long countByExample(OrderKitchenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int deleteByExample(OrderKitchenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int deleteByPrimaryKey(Integer detaillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int insert(OrderKitchen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int insertSelective(OrderKitchen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    List<OrderKitchen> selectByExample(OrderKitchenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    OrderKitchen selectByPrimaryKey(Integer detaillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderKitchen record, @Param("example") OrderKitchenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByExample(@Param("record") OrderKitchen record, @Param("example") OrderKitchenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByPrimaryKeySelective(OrderKitchen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_kitchen
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByPrimaryKey(OrderKitchen record);
}