package com.shu.onlinesell.dao;

import com.shu.onlinesell.bean.TableInfo;
import com.shu.onlinesell.bean.TableInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    long countByExample(TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int deleteByExample(TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int deleteByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int insert(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int insertSelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    List<TableInfo> selectByExample(TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    TableInfo selectByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") TableInfo record, @Param("example") TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByExample(@Param("record") TableInfo record, @Param("example") TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByPrimaryKeySelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Sun Apr 21 01:34:44 CST 2019
     */
    int updateByPrimaryKey(TableInfo record);
}